### ISSUE TITLE
How to update without SSO?

### ISSUE THREAD

**Issue by SpencerDub** [YunoHost-Apps/wordpress_ynh#107]
Previously, my WordPress installation was on a shared host. When I started my YunoHost server, I installed wordpress_ynh and then copied the database over from my shared host. This included copying my user table.

Because wordpress_ynh includes a single sign-on (SSO) plugin, every time I update wordpress_ynh via the YunoHost admin panel, it re-establishes my YunoHost user as the user for WordPress. But this doesn't match my users table, and even if it did, I don't want to use that account anyway. I have an established user on my WordPress installation that predates my YunoHost server. I don't want to create a new user account on WordPress.

Additionally, because of this user issue, whenever I update wordpress_ynh via the YunoHost admin panel, I am locked out of my admin panel until I SSH into my server and delete/rename the SSO plugin.

I know how to disable and uninstall plugins from within WordPress, but every time I update wordpress_ynh via YunoHost, the SSO plugin is reinstalled and re-enabled. How can I stop this behavior? I have no need for SSO.

Thank you.

**Comment by kay0u** [comment]
Hi!

With the [new permission system](https://github.com/YunoHost-Apps/wordpress_ynh/pull/128) it's something you can do easily.
It should be available in the stable version soon, but you can try the testing version with :

```
sudo yunohost app upgrade wordpress -u https://github.com/YunoHost-Apps/wordpress_ynh/tree/testing --debug
```

To be able to disable YunoHost accounts in WordPress, you can remove the `wordpress.admin` permission from all your users, and add it to the `Visitors` group only (in the YunoHost web admin).
