### ISSUE TITLE
PHP version issue : requirements update to 7.2

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/wordpress_ynh#113]
Last week my WordPress was running fine, but now I have this message: `Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.0". You are running 7.0.33[…]`
I did not make any upgrade, and I don't think I received a message about any automatic update.

How can I solve this issue ? Will Yunohost package switch to another php version ?

edit: upgrade fails too because of that error

**Comment by lapineige** [comment]
🆙 ? :)

(and ping #114 #95)

**Comment by kay0u** [comment]
Hi, I assume that you are still in stretch?
I reinstalled a stretch version to test it, and everything works with php 7.0. You probably have a plugin that requires a more recent version of php. In my opinion, the easiest way to solve this problem is to migrate to buster.

**Comment by lapineige** [comment]
I am.
I'll try to disable all plugins. 

I'll see how I can migrate, as it's a VPS server that I can't debug if something really bad happens I'm a little bit unadventurous, and kind of waiting for other people to test it first :sweat_smile:

**Comment by lapineige** [comment]
I don't find a wait to disable all plugins using the command line… it prompts me the php version error 😅

**Comment by lapineige** [comment]
Ok I removed the plugin folder (it was easy to find the one causing the issue: it was the last updated one), now everything is working correctly again :slightly_smiling_face:

Now I need to migrate to buster to get PHP >7.2 and use the plugin again ^^

**Comment by kay0u** [comment]
Fixed by https://github.com/YunoHost-Apps/wordpress_ynh/pull/116

**Comment by lapineige** [comment]
And by a migration to buster in my case. Thanks for the work 👍
