### ISSUE TITLE
Wordpress et php 7.4

### ISSUE THREAD

**Issue by obistro** [YunoHost-Apps/wordpress_ynh#114]
Bonjour,

Wordpress recommande d'utiliser au moins la version 7.4 de php. Ci-dessous l'explication fournie par Wordpress:

PHP est le langage de programmation utilisé pour construire et maintenir WordPress. Les nouvelles versions de PHP sont plus rapides et plus sécurisées, de sorte que rester à jour aidera les performances globales et la sécurité de votre site. La version minimale recommandée de PHP est 7.4.

Bon courage!

**Comment by alexAubin** [comment]
Closing because it's now using 8.0
