### ISSUE TITLE
Installation Wordpress sur raspberry pi

### ISSUE THREAD

**Issue by mic-rigaud** [YunoHost-Apps/wordpress_ynh#12]
Bonjour,

J'essaye d'installer wordpress sur raspberry pi.
L'installation échoue par l'interface d'administration. Du coup, j'ai essayé en ligne de commande:
yunohost app install https://github.com/YunoHost-Apps/wordpress_ynh
j'ai l'erreur suivante:
ERROR 1146 (42S02) at line 1: Table 'wordpress.wp_options' doesn't exist
Après quelques recherches il semble que ce soit un problème de base de données ou de permission sur la base de données. Avez vous une idée sur la façon de résoudre ce problème?

**Comment by maniackcrudelis** [comment]
Salut,

Je soupçonne peut-être une installation trop longue de wordpress.
Tu devrais trouver le log complet de l'installation dans le fichier /var/log/yunohost/yunohost-cli.log

Tu peux me l'envoyer en utilisant le pastebin de Yunohost

```
sudo cat /var/log/yunohost/yunohost-cli.log | yunopaste
```

**Comment by mic-rigaud** [comment]
Merci pour votre aide.
Voici le lien vers le pastebin. J'ai mis les 100 dernières lignes (fichier trop grand sinon).
https://paste.yunohost.org/
Si ca suffit pas, hésitez pas à me le dire.

**Comment by maniackcrudelis** [comment]
Hélas, les 100 dernières lignes démarrent juste au moment de l'erreur SQL, donc je n'ai pas le contexte, qui était le plus intéressant ;)
Donc je veux bien, les 150 ou 200 dernières plutôt.

Par contre, j'ai édité ton commentaire pour retirer l'adresse de ton pastebin, car il faudrait que tu vires les commandes mysql en -u root, sinon on voit ton mot de passe root sql...

**Comment by mic-rigaud** [comment]
Merci beaucoup pour avoir supprimé le lien. Je n'avais pas remarqué que mes mots de passes étaient en clair dans les log... Pour le moment mon raspberry est qu'en local. Mais on sait jamais, je vais regarder pour changer le mot de passe...

Sinon j'ai poster les lignes qui devrait t'intéresser. Normalement, j'ai enlevé les mots de passes.
https://paste.yunohost.org/fubukefewe

**Comment by maniackcrudelis** [comment]
C'est bien ce que je pensais, wordpress dispose de 30 secondes maximum pour peupler sa base de donnée. C'est surestimé en principe, mais pas sur un raspy...
Donc le script enchaîne alors que la base de donnée n'est manifestement pas prête.

Je regarde ça ce soir, pour rallonger la tempo et ajouter un avertissement.

**Comment by mic-rigaud** [comment]
Merci beaucoup.

**Comment by maniackcrudelis** [comment]
Tu peux retenter l'installation, ça devrait passer sans problème cette fois.

**Comment by mic-rigaud** [comment]
Installation réussi. Merci!
