### ISSUE TITLE
wp-config.php permission denied

### ISSUE THREAD

**Issue by lolusab** [YunoHost-Apps/wordpress_ynh#122]
Hi !
This morning, I had a blank page to my WordPress instance.
I don't have saw other issues about this.

In nginx error log :
```
2021/01/07 10:04:12 [error] 12228#12228: *38434 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/www/wordpress/wp-config.php): failed to open stream: Permission denied in /var/www/wordpress/wp-load.php on line 37PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/wordpress/wp-config.php' (include_path='.:/usr/share/php') in /var/www/wordpress/wp-load.php on line 37" while reading response header from upstream, client: <IP>, server: <subdomain>.<hostname>.fr, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm-wordpress.sock:", host: "<subdomain>.<hostname>.fr"
```

perms for wp-config.php : 
```
-rw------- 1 root root 3046 Dec 29 10:09 wp-config.php
```

Temporary fix : 
I have changed file mode to 640 and group to the user of WordPress for wp-config.php file

Should I put this change in the install / upgrade script or isn't the source of the problem this?

Thanks !

**Comment by kay0u** [comment]
Hi!

That's really strange because the permission should be 644 by default (owned by root user & group). Did you play with permissions in your server?

Your temporary fix sounds legit, and better than the actual 644. PR are indeed welcome :+1: 

Thank you for your feedback

**Comment by lolusab** [comment]
> Did you play with permissions in your server?

I didn't play with permissions, but this WordPress site is a site resulting from a migration from another Yunohost instance.

Thanks for your reply, I will make a PR to put this change in install/upgrade scripts
