### ISSUE TITLE
Log in link redirects to the instance portal.

### ISSUE THREAD

**Issue by petesimonic** [YunoHost-Apps/wordpress_ynh#130]
Strange things are observed, sirs.

When *Log in* is clicked it sends user to *Ynh portal* @ <yunohost/sso/> instead of Wp admin.

The server was reinstantiated from system snapshot with external utilities. Though no other features were impacted. And no evidence that there is a connection with this one.

Did someone experienced this type of bug, or can I provide something to debug it?

**Comment by kay0u** [comment]
Is it a bug, or a feature?

Does this user belong to the Wordpress Admin permission?

**Comment by petesimonic** [comment]
Let me test admin too. I meant internal interface to add posts and so on, not the admin privileges. And as an *editor* he always used this.

OK, after log in as the admin, applying WP upgrade, and server reboot (which separately was already done), internal interface became available to user. He also indicated that used password reset to log in initially, but SSO now seems to work.
