### ISSUE TITLE
Double authentication to administer wordpress sites is adding quite some complexities

### ISSUE THREAD

**Issue by eauchat** [YunoHost-Apps/wordpress_ynh#133]
Sorry to report a bug that was probably meant to be a feature, but since recent updates, to access the wordpress admin panel, users must first login to the SSO.
I guess this was implemented on purpose, and also adds a layer of protection and fail2ban support, I imagine, to the wordpress administration section. However this means two things:
 - one needs to login twice (first to the SSO, and then again to wordpress), which is a bit cumbersome and not so straightforward for site admins
 - site admins must have a yunohost account (which wasn't necessary in the past) and creating additional site admins account is a bit strange, you need first to create an account in yunohost, but it doesn't seem to create an account in wordpress, so then you need to create an account in wordpress interface, it's a bit confusing and cumbersome because you're creating two different accounts for the same person, and what if you reset the password of one, doesn't seem the password of the other will be.

I don't know, maybe I'm not really getting something, but the new situation even lead to some site admins not being able to log in (as detailed in #131). So it made me wonder if the security gain is really remarkable and worth the degradations.

What do you think ? Sorry, maybe this is a bit more a discussion than an issue.

**Comment by nqb** [comment]
Hello @eauchat,

I think this change has been introduced to fix #98.

**Comment by eauchat** [comment]
Hey @nqb,
Thanks for pointing me out to the origin of the changes :)
I also tend to agree with the proposals of lapineige in that thread, also seeing the new issues that came out with the modifications. Maybe if the need to login to the sso could be just optional and chosen when installing, that would allow to revert to the previous situation for people who need it. Or maybe there are better fixes to the issues I mentioned.
I don't know how much work those two approaches involve though.

**Comment by kay0u** [comment]
Hi!

To avoid the double authentication, you can allow "Visitors" to the wordpress admin permission.
This is useful when an admin is not a Ynh user for example.

**Comment by eauchat** [comment]
Hey @kay0u, thank you for the tip, I should have thought of it, it makes total sense, that resolves indeed the issues I was mentioning, cool :)
I'll close this issue then.

There is still one thing I'm wondering, about creating users, do you confirm that users should be created twice, once in yunohost and one in wordpress? I'm a bit confused, because it seems like the list of users should be synchronized to the yunohost LDAP database, no? Wondering if I should open a separate issue about that.

**Comment by kay0u** [comment]
> There is still one thing I'm wondering, about creating users, do you confirm that users should be created twice, once in yunohost and one in wordpress? I'm a bit confused, because it seems like the list of users should be synchronized to the yunohost LDAP database, no? Wondering if I should open a separate issue about that.

In the YunoHost admin interface, if you create a user and give him access to the Wordpress admin permission, the user should be able to login to the Wordpress admin interface.

**Comment by eauchat** [comment]
Just tested it, indeed users can login to the wordpress interface if they have the appropriate permission. However they still are not site admin in wordpress.

After trying different ways to add site admins, this is what I understood, you can add a site admin in two different ways:
 - login to the wordpress admin interface, add a user in it with the same username as the corresponding yunohost user, create the account and set it to be admin of the website, it will generate a random password, but this password doesn't matter in fact, because the user will just login to wordpress with it's usual yunohost password (which is cool by the way), then add the wordpress admin permission to this yunohost user
 OR
 - add the wordpress admin permission to the yunohost user, login to wordpress with this user, this will add it to the list of users in wordpress, then login with the admin account to wordpress, and set the newly listed user as website admin

I feel I'm making it more complicated than it is, and I totally understand that there's probably not much any way to make it easier to put together wordpress logic and yunohost logic.
I don't want to be annoying and this is really not a very big issue. Maybe just a good thing would be to add a line about this in the README. But even without it it's fine, since it's working good.

If you also think that's of any use to add this line in the README, I can try to do it :)
