### ISSUE TITLE
Wordpress page protégée par mot de passe

### ISSUE THREAD

**Issue by michelwend** [YunoHost-Apps/wordpress_ynh#140]
Bonjour,
J'utilise yunohost avec wordpress à jour. Je souhaite créer une page protégée par mot de passe. Mais lorsque je fais un test en étant connecté en mode admin sur wordpress j'arrive sur le sso de yunohost. Si je tape directement le lien de la page j’arrive par contre à un message qui m'indique que je ne peux pas autorisé à voir le contenu. Voici le lien avec les captures d'écran sur le forum de yunohost:
[https://forum.yunohost.org/t/wordpress-page-protegee-par-mot-de-passe/16194](https://forum.yunohost.org/t/wordpress-page-protegee-par-mot-de-passe/16194).
Si vous avez éventuellement une idée de solution ou de paramétrage yunohost avec wordpress, cela pourrait m'aider. En vous remerciant.

**Comment by kay0u** [comment]
Fixed in the forum
