### ISSUE TITLE
Admin login with 2 wordpress in the same server in separate domains

### ISSUE THREAD

**Issue by xaloc33** [YunoHost-Apps/wordpress_ynh#149]
### Describe the bug

I have 2 wordpress installed in the root of 2 domains, first one works fine but I cannot login to the second admin page (wp-login.php not found/ invalid URL).

### Context

- Hardware: lxc container in a VPS
- YunoHost version: 4.3.2.2
- I have access to my server: Through SSH & through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

Install wordpress in root of one domain, install wordpress in root of second domain, try to access admin panel of second wordpress. Even when the second wordpress is installed in a path of the second domain the wordpress admin panel remains inaccessible.

### Expected behavior

Being able to access both wordpress admin panels

### Logs

On NGINX logs for the second domain:
```bash
"GET /wp-login.php HTTP/2.0" 302 426 "https://domain1/" "http-user-agent"
```
Not sure why it shows domain1 instead of 2, tried to look at the NGINX config but not sure what or where to change something.

**Comment by kay0u** [comment]
I can't reproduce the bug.

Do you have any redirection in the `/etc/ssowat/conf.json.persistent` file? Can I get more logs from nginx and php-fpm to understand what is going on?

**Comment by xaloc33** [comment]
There was nothing on `/etc/ssowat/conf.json.persistent`. I think that there is that if the admin page of `domain2` is set to private it needs to log on from `domain1` as a YunoHost user and when trying to access `domain2/wp-login.php` it seems to redirect to the wrong domain. Setting `domain2/wp-login.php` to public seems to solve the issue.
Thanks for the help it is definitely something about the ssowat config.
