### ISSUE TITLE
Accessing uploaded files broken since PR 155

### ISSUE THREAD

**Issue by lx242** [YunoHost-Apps/wordpress_ynh#156]
### Describe the bug

With [PR 155](https://github.com/YunoHost-Apps/wordpress_ynh/pull/155) media upload is broken due to problems with access rights.
Files uploaded will be properly uploaded to the server, thumbnails are created properly, but the new files are not accessible. Preview images stay empty.

When installing last version before PR 155 (https://github.com/YunoHost-Apps/wordpress_ynh/commit/e0c54b84abc3719d83a3f2fda243e690760270a6) file upload works as expected.

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH && through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: https://github.com/YunoHost-Apps/wordpress_ynh/commit/a42dbf35fde78effd3513fc0c734f78e7457dcca
- If upgrading, current package version: 5.8~ynh1

### Steps to reproduce

- ```sh
    sudo yunohost app install wordpress
    ```
- In WP Admin panel `https://<hidden>/wptest/wp-admin/`
   1. Navigate to media (`wptest/wp-admin/upload.php`)
   2. Click on button "Add New"
   3. Select and upload any image file from your local system
   4. Watch progress bar complete
   5. Observe blank preview image
   6. Developer tools reveal response status 404 from server
   7. checking nginx error logs show
       ```plain
          2022/03/21 07:22:05 [crit] 9807#9807: *1993 stat() "/var/www/wordpress__4/wp-content/uploads/2022/03/noisehd-300x169.png" failed (13: Permission denied), client: <hidden>, server: <hidden>, request: "GET /wptest/wp-content/uploads/2022/03/noisehd-300x169.png HTTP/2.0", host: "<hidden>", referrer: "https://<hidden>/wptest/wp-admin/upload.php"
       ```

### Expected behavior

Access rights should be granted in a way that the serving process is able to read uploaded files.

### Logs

https://paste.yunohost.org/raw/tafuvogoyi

### Screenshot

![image](https://user-images.githubusercontent.com/60870930/159220540-a9b3b27f-b540-4730-9dfb-60094db3b131.png)

**Comment by ghost** [comment]
Same issue here. 
```
chmod 755 -R uploads
```
resolve the problem.

**Comment by tituspijean** [comment]
The issue lies in the fact that the PHP-FPM config runs with wordpress as both user and group. 

```
[__APP__]
user = __APP__
group = __APP__

...
```

However PR 155 makes the group `www-data`.

@yalh76, shall we change the PHP configuration or the file ownership?

**Comment by yalh76** [comment]
> 

I don't know :/

There wasn't changes made on php-fpm in #155

**Comment by tituspijean** [comment]
No indeed, but it changes the files group ownership. ;)

**Comment by ajroach42** [comment]
Can confirm. Updating file ownership back does make the media visible again. I assume we could also update group membership? 

I'm not sup[er familiar with the yunohost internals, but I used to be pretty well versed in wordpress. Happy to take a crack at a solution if no one else is available.

**Comment by tituspijean** [comment]
OK I think I found the issue(s):

1. NGINX runs on user `www-data`, PHP-FPM default config makes it run on user and group `$app`. Files written by PHP-FPM will look like they were `chmod $app:$app`
2. The app now `chmod 750` and `chown $app:www-data` all the directories.
3. Somehow, Wordpress' `/wp-content/uploads` directory is only created when a new media is uploaded. Both the directory and the media files thus get the `$app:$app` ownership from PHP-FPM, preventing NGINX from reading them.

I am working on a fix with ACLs.

**Comment by tituspijean** [comment]
OK I think I found the issue(s):

1. NGINX runs on user `www-data`, PHP-FPM default config makes it run on user and group `$app`. Files written by PHP-FPM will look like they were `chmod $app:$app`
2. The app now `chmod 750` and `chown $app:www-data` all the directories.
3. Somehow, Wordpress' `/wp-content/uploads` directory is only created when a new media is uploaded. Both the directory and the media files thus get the `$app:$app` ownership from PHP-FPM, preventing NGINX from reading them.

I am working on a fix with ACLs.

**Comment by tio-trom** [comment]
What would be a temporary fix then? Instead of manually chmod the uploads folder every time I upload new images :P

**Comment by zamentur** [comment]
```
chown -R $app:www-data /var/www/$app/wp-content/uploads
chmod g+s /var/www/$app/wp-content/uploads
chmod g+s $(find /var/www/$app/wp-content/uploads -type d)
```

**Comment by tio-trom** [comment]
> ```
> chown -R $app:www-data /var/www/$app/wp-content/uploads
> chmod g+s /var/www/$app/wp-content/uploads
> chmod g+s $(find /var/www/$app/wp-content/uploads -type d)
> ```

Is this going to fix it for good? No need to do this every time I upload media to Wordpress? And thanks!

**Comment by jakobkilian** [comment]
Same issue here. Suggested fix by [zamentur](https://github.com/zamentur) does not work for new uploads in my case (it only works for the scaling variants generated by WP, to be precise). Don't really undestand the linked issues' state: will that be fixed soon or is there a workaround? Thanks a lot!

**Comment by tio-trom** [comment]
I too am eager for the update. It is a very big issue if people cannot upload and see any media in wordpress. They may think the entire wp is broken. Any release date for the fix? Thanks for your work!

**Comment by tituspijean** [comment]
I'm very confused by this issue. Can y'all share your setup? All on YunoHost 4?
I have tested the current WordPress without the PR I made.

---

## On YunoHost 4 on WSL with PHP7.3 it works:

```
 ⚡ root@WSL # yunohost -v
yunohost:
  repo: stable
  version: 4.3.6.2
yunohost-admin:
  repo: testing
  version: 4.3.4.1
moulinette:
  repo: stable
  version: 4.3.3.1
ssowat:
  repo: stable
  version: 4.3.3.1
 ⚡ root@WSL # ls -la /var/www/wordpress/wp-content/uploads/2022/05/
total 20
drwxr-xr-x 2 wordpress wordpress 4096 May 18 20:07 .
drwxr-xr-x 3 wordpress wordpress 4096 May 18 20:07 ..
-rw-r--r-- 1 wordpress wordpress 6094 May 18 20:07 S9WjhbBRpM-lPlbp.uBGCTzrF.png
-rw-r--r-- 1 wordpress wordpress 2350 May 18 20:07 bazarr.png
 ⚡ root@WSL # cat /etc/php/7.3/fpm/pool.d/wordpress.conf

[wordpress]

user = wordpress
group = wordpress

chdir = /var/www/wordpress

listen = /var/run/php/php7.3-fpm-wordpress.sock
listen.owner = www-data
listen.group = www-data

pm = static
pm.max_children = 48
pm.max_requests = 500
request_terminate_timeout = 1d

; Additional php.ini defines, specific to this pool of workers.

php_admin_value[upload_max_filesize] = 50M
php_admin_value[memory_limit] = 64M
php_admin_value[post_max_size] = 50M
```
![image](https://user-images.githubusercontent.com/8769166/169119305-c9602f12-879d-451e-a771-dff17fd45144.png)

---

## On YunoHost 4 on a VPS with PHP7.3 it does NOT work:

```
 admin@vps4 # sudo su
root@hlxmnt:/home/admin# yunohost -v
yunohost:
  repo: stable
  version: 4.3.6.2
yunohost-admin:
  repo: testing
  version: 4.3.4.1
moulinette:
  repo: stable
  version: 4.3.3.1
ssowat:
  repo: stable
  version: 4.3.3.1

admin@vps4 # ls -la /var/www/wordpress/wp-content/uploads/2022/05/
total 20
drwxr-x--- 2 wordpress wordpress 4096 May 18 18:19 .
drwxr-x--- 3 wordpress wordpress 4096 May 18 18:19 ..
-rw-r----- 1 wordpress wordpress 2350 May 18 18:19 bazarr.png
-rw-r----- 1 wordpress wordpress 6094 May 18 18:19 S9WjhbBRpM-lPlbp.uBGCTzrF.png

admin@vps4 # cat /etc/php/7.3/fpm/pool.d/wordpress.conf

[wordpress]

user = wordpress
group = wordpress

chdir = /var/www/wordpress

listen = /var/run/php/php7.3-fpm-wordpress.sock
listen.owner = www-data
listen.group = www-data

pm = static
pm.max_children = 8
pm.max_requests = 500
request_terminate_timeout = 1d

; Additional php.ini defines, specific to this pool of workers.

php_admin_value[upload_max_filesize] = 50M
php_admin_value[memory_limit] = 64M
php_admin_value[post_max_size] = 50M
root@hlxmnt:/home/admin# cat /etc/php/7.3/fpm/pool.d/wordpress.conf

[wordpress]

user = wordpress
group = wordpress

chdir = /var/www/wordpress

listen = /var/run/php/php7.3-fpm-wordpress.sock
listen.owner = www-data
listen.group = www-data

pm = static
pm.max_children = 8
pm.max_requests = 500
request_terminate_timeout = 1d

; Additional php.ini defines, specific to this pool of workers.

php_admin_value[upload_max_filesize] = 50M
php_admin_value[memory_limit] = 64M
php_admin_value[post_max_size] = 50M
```

![image](https://user-images.githubusercontent.com/8769166/169120339-0e35990b-4126-488b-b997-11df8c1b347e.png)

---

## On YunoHost 11 on a VPS with PHP7.4 it does NOT work:

```
 ⚡ root@VPS11  /home/admin  yunohost -v
yunohost:
  repo: testing
  version: 11.0.7
yunohost-admin:
  repo: testing
  version: 11.0.7
moulinette:
  repo: testing
  version: 11.0.7
ssowat:
  repo: testing
  version: 11.0.7

 ⚡ root@VPS11  /home/admin  ls -la /var/www/wordpress/wp-content/uploads/2022/05/
total 20
drwxr-x--- 2 wordpress wordpress 4096 May 18 20:17 .
drwxr-x--- 3 wordpress wordpress 4096 May 18 20:10 ..
-rw-r----- 1 wordpress wordpress 2350 May 18 20:10 bazarr.png
-rw-r----- 1 wordpress wordpress 6094 May 18 20:17 S9WjhbBRpM-lPlbp.uBGCTzrF.png

 ✘ ⚡ root@VPS11  /home/admin  cat /etc/php/7.4/fpm/pool.d/wordpress.conf

[wordpress]

user = wordpress
group = wordpress

chdir = /var/www/wordpress

listen = /var/run/php/php7.4-fpm-wordpress.sock
listen.owner = www-data
listen.group = www-data

pm = static
pm.max_children = 4
pm.max_requests = 500
request_terminate_timeout = 1d

; Additional php.ini defines, specific to this pool of workers.

php_admin_value[upload_max_filesize] = 50M
php_admin_value[memory_limit] = 64M
php_admin_value[post_max_size] = 50M
```

![image](https://user-images.githubusercontent.com/8769166/169121089-80ec8407-7690-440f-82bd-afd0f362e498.png)

**Comment by tio-trom** [comment]
I am on a VPS with php 7.3 and YNH 4.3.6.3 (stable). Fresh install of YNH and Wordpress.

**Comment by theRAGEhero** [comment]
> > ```
> > chown -R $app:www-data /var/www/$app/wp-content/uploads
> > chmod g+s /var/www/$app/wp-content/uploads
> > chmod g+s $(find /var/www/$app/wp-content/uploads -type d)
> > ```
> 
> Is this going to fix it for good? No need to do this every time I upload media to Wordpress? And thanks!

Could please someone confirm that this workaround works?

Do I have to change $app with wordpress__x to make it work?

I agree that is important to find a way, also manual or temporary, to fix it,

Thank you.

**Comment by tituspijean** [comment]
> Could please someone confirm that this workaround works?

Works for me.

> Do I have to change $app with wordpress__x to make it work?

Yes. Or only `wordpress` if you have only one instance.

> I agree that is important to find a way, also manual or temporary, to fix it,

Thank you for testing.

**Comment by jakobkilian** [comment]
I am on a Hetzner VPS with 4.3.6.3 (stable) and "php7.3-fpm" & "php8.0-fpm" service running in ynh. 
The workaround only solves the problem for existing files not for newly uploaded...

EDIT: Wordpress Config:
- Server	`nginx/1.14.2	`
- PHP	`v7.3.33-1+0~20211119.91+debian10~1.gbp618351	`
- MYSQL	`v10.3.34-MariaDB-0+deb10u1`

**Comment by tituspijean** [comment]
Can you share the output of `sudo ls -la /var/www/wordpress/wp-content/uploads/2022/05/` ? You can hide filenames if you prefer.

**Comment by tio-trom** [comment]
```
chown -R $app:www-data /var/www/$app/wp-content/uploads
chmod g+s /var/www/$app/wp-content/uploads
chmod g+s $(find /var/www/$app/wp-content/uploads -type d)
```

Actually this fixed it for me even for newly uploaded files. On two separate servers. php 7.3 and YNH 4.3.6.3 (stable)

**Comment by jakobkilian** [comment]
Very Much!
Uploaded one file (the lower) did the chown workaround and then uploaded a second ("new-upload.png"). Still has the wordpress:wordpress ownership, but only for the uncropped version.

```
-rw-rw----+ 1 wordpress www-data   45194 May 22 20:15 new-upload-150x150.png
-rw-rw----  1 wordpress wordpress 159554 May 22 20:15 new-upload.png
-rw-rw----+ 1 wordpress www-data   45194 May 22 20:14 upload-modified-with-chown-150x150.png
-rw-rw----  1 wordpress www-data  159554 May 22 20:14 upload-modified-with-chown.png
```

**Comment by tituspijean** [comment]
I see you have ACLs, what are their settings?

`sudo getfacl /var/www/wordpress/wp-content/uploads/`

Iff you applied one of my previous attempts, you can remove them, we dropped the ACL idea:

`sudo setfacl -bk /var/www/wordpress/wp-content/uploads/`

Can you share `sudo ls -la /var/www/wordpress/wp-content/uploads/` and `sudo ls -la /var/www/wordpress/wp-content/uploads/2022` too? Looks like the sticky bit `s` is not applied.

**Comment by jakobkilian** [comment]
> `sudo getfacl /var/www/wordpress/wp-content/uploads/`

Can't say for sure if I set acl stuff at some point. 
**Output:**
```
getfacl: Removing leading '/' from absolute path names
# file: var/www/wordpress/wp-content/uploads/
# owner: wordpress
# group: www-data
# flags: -s-
user::rwx
user:wordpress:rwx
user:omid:rwx
group::r-x
mask::rwx
other::---
default:user::rwx
default:user:wordpress:rwx
default:user:omid:rwx
default:group::r-x
default:mask::rwx
default:other::---
```

> `sudo setfacl -bk /var/www/wordpress/wp-content/uploads/`

Ok, did that, but there is no change in behaviour. 

> Can you share `sudo ls -la /var/www/wordpress/wp-content/uploads/` and `sudo ls -la /var/www/wordpress/wp-content/uploads/2022` too? Looks like the sticky bit `s` is not applied.

**Output for "uploads":**
```
total 28
drwxr-s---  4 wordpress www-data 4096 May 20 21:45 .
drwxrws---+ 6 wordpress www-data 4096 May 22 19:48 ..
drwxrws---+ 3 wordpress www-data 4096 May 17 14:39 2022
drwxrws---+ 2 wordpress www-data 4096 May 20 21:45 wpcf7_uploads
```

**Output for "uploads":**
```
total 20
drwxrws---+ 3 wordpress www-data 4096 May 17 14:39 .
drwxr-s---  4 wordpress www-data 4096 May 20 21:45 ..
drwxrws---+ 2 wordpress www-data 4096 May 22 20:15 05
```

**Comment by tituspijean** [comment]
You still have ACLs (`+` symbol). 😖  What's the output of `sudo getfacl /var/www/wordpress/` ?)

**Comment by jakobkilian** [comment]
> What's the output of `sudo getfacl /var/www/wordpress/` ?)

```
getfacl: Removing leading '/' from absolute path names
# file: var/www/wordpress/
# owner: wordpress
# group: www-data
# flags: -s-
user::rwx
user:wordpress:rwx		#effective:r-x
user:omid:rwx			#effective:r-x
group::r-x
mask::r-x
other::---
default:user::rwx
default:user:wordpress:rwx
default:user:omid:rwx
default:group::r-x
default:mask::rwx
default:other::---
```

**Comment by tituspijean** [comment]
What's the `omid` user? If you do not use it, you can delete ACLs there too: `sudo setfacl -Rbk /var/www/wordpress/`
Re-apply the commands afterwards:

```
app=wordpress
chown -R $app:www-data /var/www/$app/wp-content/uploads
chmod g+s /var/www/$app/wp-content/uploads
chmod g+s $(find /var/www/$app/wp-content/uploads -type d)
```

**Comment by jakobkilian** [comment]
Omid is a user that I granted sftp access by doing [this](https://yunohost.org/de/sftp_on_apps). The issue was there before I did that.

> sudo setfacl -Rbk /var/www/wordpress/

So I did delete all ALCs on `wordpress` and also on `wordpress/uploads`
Then did the chown & chmod fix you posted. 
Same behaviour:

```
-rw-r----- 1 wordpress www-data   45194 May 23 09:45 new-upload-150x150.png
-rw-r----- 1 wordpress wordpress 159554 May 23 09:45 new-upload.png
```

I didn't change a lot int this wp instance. But if it helps, I can reinstall it and do some troubleshooting with a fresh install? We can also have a chat if that is quicker? Just tell me if you need anything!

**Comment by tituspijean** [comment]
If you're ready to get adventurous, I would advise you to try out the testing branch including that fix:

`sudo yunohost app upgrade wordpress -u https://github.com/YunoHost-Apps/wordpress_ynh/tree/5.9.3_PHP8 -f`

Otherwise I'm available tonight on Matrix.

**Comment by jakobkilian** [comment]
I would love to test, but would need to upgrade to ynh11 for that. As other things on the server are important, I cannot do that right now. 
uhm how would we connect on Matrix? Here's no DM function...

**Comment by tituspijean** [comment]
Oh sorry, indeed that branch is for Bullseye. Try this one: `sudo yunohost app upgrade wordpress -u https://github.com/YunoHost-Apps/wordpress_ynh/tree/perms -f`

To connect to Matrix (or IRC, they are bridged): https://yunohost.org/en/chat_rooms
If you don't have any clients, let's chat in the Apps packaging room with that link: https://web.libera.chat/#yunohost-apps for IRC, or https://matrix.to/#/#yunohost-apps:matrix.org (Matrix)

**Comment by jakobkilian** [comment]
Upgrade didn't work for me ("already up to date").
Deinstalled WP and used `sudo yunohost app install https://github.com/YunoHost-Apps/wordpress_ynh/tree/perms -f --debug` to install the "perm" branch. 
With the fresh install I still have the issue:
```
-rw-r----- 1 wordpress www-data   45194 May 23 12:55 new-upload-150x150.png
-rw-r----- 1 wordpress wordpress 159554 May 23 12:55 new-upload.png
```

Also tried the chown & chmod workaround. Same behaviour (cropped img gets right group, original stays wordpress:wordpress).

**Comment by ghost** [comment]
I had this problem, and just with that, it's ok, without problem after months : 
```
chmod 755 -R uploads
```
the owner isn't important I think : I've on my wordpress this : 
```
drwxr-xr-x  8 wordpress__2 www-data       4096 Mar 22 02:36 2021
drwxr-xr-x  5 wordpress__2 wordpress__2   4096 Apr 30 22:06 2022
```
And I can see all my medias, add new medias, with any problem. 
on yunohost 4.3.6.3 (stable), php 7.3

**Comment by jakobkilian** [comment]
thx [Cellophile](https://github.com/Cellophile): 

`chmod 755 -R uploads` solves the issue for me, too. Can anyone confirm, that this is a practicable way (e.g. without affecting security?)

**Comment by ghost** [comment]
Maybe `chmod 754 -R uploads` would be safer ?

**Comment by tio-trom** [comment]
So although I said this solution worked:
```
chown -R $app:www-data /var/www/$app/wp-content/uploads
chmod g+s /var/www/$app/wp-content/uploads
chmod g+s $(find /var/www/$app/wp-content/uploads -type d)
```
It does not work for the full size images....only for the converted ones (thumbnails and such). 

EDIT: perhaps with sudo and as root this seems to work...I am confused a bit.
EDIT2: no it does not work for the original image uploaded. Only works for the converted versions.

**Comment by theRAGEhero** [comment]
> > Could please someone confirm that this workaround works?
> 
> Works for me.
> 
> > Do I have to change $app with wordpress__x to make it work?
> 
> Yes. Or only `wordpress` if you have only one instance.
> 
> > I agree that is important to find a way, also manual or temporary, to fix it,
> 
> Thank you for testing.

Thank you!

The first two commands run well (with sudo), the last one doesn't work.

```
admin@home:~$ sudo chmod g+s $(find /var/www/wordpress__7/wp-content/uploads -type d)
find: ‘/var/www/wordpress__7/wp-content/uploads’: Permission denied
chmod: missing operand after ‘g+s’
Try 'chmod --help' for more information.
admin@home:~$
```

am I doing it wrong? 

Thank you.

**Comment by Gofannon** [comment]
If it can help the packagers, I was able to fix it like this:



**php errors logs**

```bash
root@myserver:~# tail -f /var/log/nginx/myserver.net-error.log

2022/06/13 22:17:15 [crit] 19682#19682: *12774 stat() "/var/www/wordpress/wp-content/uploads/2022/04/logo.png" failed (13: Permission denied), client: XXX, server: myserver.net, request: "GET /blog/wp-content/uploads/2022/04/logo.png HTTP/2.0", host: "myserver.net", referrer: "https://myserver.net/blog/"
```


fixing user rights

```
root@myserver:~# ls -al /var/www/wordpress/wp-content/uploads/
total 28
drwxr-x--- 7 wordpress wordpress 4096 May  9 20:55 .
drwxr-x--- 7 wordpress www-data  4096 Jun 13 22:17 ..
drwxr-x--- 4 wordpress wordpress 4096 May  9 20:33 2016
drwxr-x--- 8 wordpress wordpress 4096 May  9 20:50 2017
drwxr-x--- 7 wordpress wordpress 4096 May  9 20:53 2018
drwxr-x--- 6 wordpress wordpress 4096 May  9 20:55 2019
drwxr-x--- 4 wordpress wordpress 4096 Jun  1 03:00 2022
root@myserver:~# ls -al /var/www/wordpress/wp-content/
total 32
drwxr-x--- 7 wordpress www-data  4096 Jun 13 22:17 .
drwxr-x--- 5 wordpress www-data  4096 Jun 13 03:00 ..
-rw-r----- 1 wordpress www-data    28 Jan  8  2012 index.php
drwxr-x--- 4 wordpress www-data  4096 May 10 03:00 languages
drwxr-x--- 8 wordpress www-data  4096 May 21 03:00 plugins
drwxr-x--- 6 wordpress www-data  4096 Jun  3 03:00 themes
drwxr-x--- 2 wordpress www-data  4096 Jun 10 03:00 upgrade
drwxr-x--- 7 wordpress wordpress 4096 May  9 20:55 uploads
root@myserver:~# chown -R wordpress:www-data /var/www/wordpress/wp-content/uploads/
root@myserver:~# 
root@myserver:~# 
root@myserver:~# ls -al /var/www/wordpress/wp-content/
total 32
drwxr-x--- 7 wordpress www-data 4096 Jun 13 22:17 .
drwxr-x--- 5 wordpress www-data 4096 Jun 13 03:00 ..
-rw-r----- 1 wordpress www-data   28 Jan  8  2012 index.php
drwxr-x--- 4 wordpress www-data 4096 May 10 03:00 languages
drwxr-x--- 8 wordpress www-data 4096 May 21 03:00 plugins
drwxr-x--- 6 wordpress www-data 4096 Jun  3 03:00 themes
drwxr-x--- 2 wordpress www-data 4096 Jun 10 03:00 upgrade
drwxr-x--- 7 wordpress www-data 4096 May  9 20:55 uploads
root@myserver:~# 
```

-------

**wordpress package (branch master)**

```bash
id: wordpress
name: WordPress
version: 5.8~ynh1
```

**Yunohost version**

```bash
yunohost --version
yunohost: 
  repo: testing
  version: 11.0.7
yunohost-admin: 
  repo: testing
  version: 11.0.7
moulinette: 
  repo: testing
  version: 11.0.7
ssowat: 
  repo: testing
  version: 11.0.7
```

**Comment by theRAGEhero** [comment]
> ```
> chown -R $app:www-data /var/www/$app/wp-content/uploads
> chmod g+s /var/www/$app/wp-content/uploads
> chmod g+s $(find /var/www/$app/wp-content/uploads -type d)
> ```
> 
> Actually this fixed it for me even for newly uploaded files. On two separate servers. php 7.3 and YNH 4.3.6.3 (stable)

So you didn't have the error I had?

> > > Could please someone confirm that this workaround works?
> > 
> > 
> > Works for me.
> > > Do I have to change $app with wordpress__x to make it work?
> > 
> > 
> > Yes. Or only `wordpress` if you have only one instance.
> > > I agree that is important to find a way, also manual or temporary, to fix it,
> > 
> > 
> > Thank you for testing.
> 
> Thank you!
> 
> The first two commands run well (with sudo), the last one doesn't work.
> 
> ```
> admin@home:~$ sudo chmod g+s $(find /var/www/wordpress__7/wp-content/uploads -type d)
> find: ‘/var/www/wordpress__7/wp-content/uploads’: Permission denied
> chmod: missing operand after ‘g+s’
> Try 'chmod --help' for more information.
> admin@home:~$
> ```
> 
> am I doing it wrong?
> 
> Thank you.

**Comment by tio-trom** [comment]
I tested with at least 10 Wordpress websites. This is still an issue. See https://github.com/YunoHost-Apps/wordpress_ynh/issues/173

**Comment by Bugsbane** [comment]
I'm having this issue, too, with the testing version of yunohost. Is there anything I can do to help with info/testing?
