### ISSUE TITLE
Please mark this package as: not-working

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/wordpress_ynh#168]
For the past weeks the Wordpress package suffers from a fatal bug. If anyone installs Wordpress they won't be able to use any media that they upload. The issue is reported here https://github.com/YunoHost-Apps/wordpress_ynh/issues/156 and no proper fix was found. The testing branch partially fixes the problem, but not for the originally uploaded media, only for the images converted after upload. So even for the testing branch this is still a major bug since no other media, except converted images, can be used in Wordpress.

This package is misleading since it is marked as High-Quality and working. I know you guys are working to find a solution but since it takes so long it is better to mark it as not working for the time being. Else people will install Wordpress and see that it doesn't work, to then come and complain to you :D . Better make them aware it is not working properly.

Thank you for your work!

**Comment by jcn50** [comment]
+1

**Comment by Gofannon** [comment]
Thanks for this information, I was puzzled to not any pictures and was wondering if I missed something on my fresh install. Now, I know

**Comment by Gofannon** [comment]
quick solve until package is fixed : https://github.com/YunoHost-Apps/wordpress_ynh/issues/156#issuecomment-1154537275

**Comment by yalh76** [comment]
#156 closed
