### ISSUE TITLE
Some suggestions for updating/packaging

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/wordpress_ynh#174]
I see you are disabling the cron by default. Why?

https://github.com/YunoHost-Apps/wordpress_ynh/blob/master/conf/wp-config.php#L22

The cron functionality is crucial for many WP plugins. At least please do not overwrite via the update process.

Second, these PHP values are too low:
```
php_admin_value[upload_max_filesize] = 50M
php_admin_value[memory_limit] = 64M
php_admin_value[post_max_size] = 50M
```
I suggest to increase to 512M. To make sure it works well. I manage over 20 Worpdress websites, some smaller, some bigger, and all benefit from an increase PHP values. Also, at least please do not overwrite these via updates.

Thanks!

**Comment by tituspijean** [comment]
> I see you are disabling the cron by default. Why?
> https://github.com/YunoHost-Apps/wordpress_ynh/blob/master/conf/wp-config.php#L22
> The cron functionality is crucial for many WP plugins. At least please do not overwrite via the update process.

It looks like it's replaced by the system's cron to avoid calling that script upon every PHP page load.
https://github.com/YunoHost-Apps/wordpress_ynh/blob/0e59f14cd3bb3fa4a1c2468638ee918e34e9bc3c/scripts/install#L255

> Second, these PHP values are too low:
> ```
>php_admin_value[upload_max_filesize] = 50M
>php_admin_value[memory_limit] = 64M
>php_admin_value[post_max_size] = 50M
>```
>I suggest to increase to 512M. To make sure it works well. I manage over 20 Worpdress websites, some smaller, some bigger, and all benefit from an increase PHP values. Also, at least please do not overwrite these via updates.

These should be tunable once the config panel feature is fixed for the app.

**Comment by tio-trom** [comment]
> It looks like it's replaced by the system's cron to avoid calling that script upon every PHP page load.

Ok but many WP plugins will detect no cron and thus either not work or complain that do not work....

> These should be tunable once the config panel feature is fixed for the app.

Ok. In the meantime maybe do not edit these values when you push an update. If anyone tweaks these values they do so because they need to.

**Comment by tio-trom** [comment]
Mind you if you don't increase those values you get a fatal error like "There has been a critical error on this website. Please check your site admin email inbox for instructions."

![2022-07-10_12-45](https://user-images.githubusercontent.com/38043315/178141629-d77fb27b-bd9a-490a-8d94-8045beca7001.png)

If you have a bunch of plugins installed.
