### ISSUE TITLE
Images uploaded seen in library and editor but NOT in preview

### ISSUE THREAD

**Issue by deljones** [YunoHost-Apps/wordpress_ynh#175]
### Describe the bug

I can upload and see in the media library newly uploaded images along with previously uploaded images. 

If I create a new post and add an image from the media library (or upload) the image can be seen in the edit mode. 

When I preview the image is not there, just a black space where the image should be. If I click on the space where the image should be I get a 403 error. 

However if I use a previously uploaded image there are no problems. 

Only images uploaded since v6 update cannot be seen in preview but are seen in edit and in the media library. 

- Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*
- YunoHost version: x.x.x
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no

### Steps to reproduce

Update Wordpress to v6 through the YUNO web admin. 

Create a new post. 
Add an image using UPLOAD.
Format the image as you wish (it will be seen)
Click preview/Desktop (image missing)
Click on the space where the image should be you will get 403 error. 

Create a new post 
Add an old image pre v6
Format the image as you wish
Click preview/Desktop
The image will appear. As expected. 

### Expected behavior

Create a new post 
Add from the Media Library or upload and image
Format the image as you wish
Save
Preview the image 
Page and image should show as in edit mode

### Logs
 I don’t know where to look

**Comment by vsatmydynipnet** [comment]
can confirm this one. will delete wordpress and reinstall 5.9.x to be able to continue setup.

**Comment by vsatmydynipnet** [comment]
sorry for another one., going back to 5.9.x does not help.

**Comment by deljones** [comment]
I don’t recall this problem pre version 6. To confirm. Going back to a previous version does not help?  That’s a real shame. Wordpress in this current version is unusable.

**Comment by vsatmydynipnet** [comment]
I definitely would appreciate a  temporary workaround if there is one to make WP work again. this one really kills all wordpress on yunohost.

**Comment by vsatmydynipnet** [comment]
I found what is causing the problem, but unsure how to fix this in yunohost:

the uploads directory is 

rwx rws for wordpress:www-data but folders below are created

rwx rwx for wordpress:www-data 

so the www-data group is not set for uploaded files, which are wordpress:wordpress and ends up in 403.  it looks like the php-fpm pool runs as wordpress, so uploads does  end up in wordpress:wordpress.

still not sure how to fix it, but continuing to search

**Comment by vsatmydynipnet** [comment]
temporary solved by

```
/home/CHANGES/etc# diff -u group.ORIG group 
--- group.ORIG	2022-07-05 10:19:15.773190228 +0200
+++ group	2022-07-05 10:16:37.105161963 +0200
@@ -70,4 +70,4 @@
 stunnel4:x:127:
 memcache:x:128:
 sogo:x:129:
-wordpress:x:997:
+wordpress:x:997:www-data
```
i am sure there is a better way, but currently i am able to continue.

**Comment by deljones** [comment]
Could you do an idiots guide on this fix. (That’s me)

dj

**Comment by vsatmydynipnet** [comment]
- Login via ssh to your server
- Edit /etc/group
  
add www-data user to group wordpress:

before:
wordpress:x:997:

after:
wordpress:x:997:www-data

save the file. i restartet nginx and php-fpm, if you are unsure reboot your server.

then everything should work. here it does.

**Comment by deljones** [comment]
@vsatmydynipnet thanks very much for this , I appreciate your help. I will try this out later and see what happens. I do hope it works for me. I’ll report back. 

Thanks 

dj

**Comment by deljones** [comment]
@vsatmydynipnet Just tried your fix... Fantastic.!!!!! Thank you so much for your work on this. Everything is right with the world. Again!
My permissions were different I had 993. I simply added :www-data to the end of it, restarted and all good... I have 4 websites on my YNH server which have been trouble-free until v6, so you can imagine the panic. Surprised that the issue has not been raised though until now, it's so obvious.

Thanks again. Good work.

Note to the guys however who do such a great job making Wordpress available to us, thanks, but please fix!!! 

dj
