### ISSUE TITLE
Does not accept credentials for wp-admin or wp-login

### ISSUE THREAD

**Issue by courtg9000** [YunoHost-Apps/wordpress_ynh#24]
I try to login with my user credentials via wp-admin and they are invalid.
Can you advise please?

**Comment by maniackcrudelis** [comment]
Yes, there is an error with the ldap plugin. I think an upgrade of this plugin break the previous config.
So, until I find how to fix this issue, you should connect to your YunoHost portal before your admin panel on wordpress. Like that, you gonna be connected by the sso.

**Comment by p3k** [comment]
I think I was able to work around the issue by reïnstalling the Simple LDAP plugin (via WP admin). Afterwards, I was able to login with my initial user account as well as the one I created after the initial one did not work…

**Comment by maniackcrudelis** [comment]
Fix here https://github.com/YunoHost-Apps/wordpress_ynh/pull/35
