### ISSUE TITLE
Unable to install / Signature issues on Sury

### ISSUE THREAD

**Issue by arpadlukacs** [YunoHost-Apps/wordpress_ynh#240]
### Describe the bug

I can't install the app. I tried using the web interface, then I tried to install the dev version using the command line, both have the same problem:

```
The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
```

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.29
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

```sh
yunohost app install https://github.com/YunoHost-Apps/wordpress_ynh/tree/testing --debug
```

### Expected behavior

Wordpress should be installed without any error.

### Logs

https://paste.yunohost.org/raw/gavulavexi

**Comment by alexAubin** [comment]
`WARNING - W: GPG error: https://packages.sury.org/php bullseye InRelease: Splitting up /var/lib/apt/lists/packages.sury.org_php_dists_bullseye_InRelease into data and signature failed`

saw this reported the other day on the forum, sounded like a temporary issue on Sury's side ...

**Comment by arpadlukacs** [comment]
Thanks, it is working now.
