### ISSUE TITLE
Add a warant about wordpress risk

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/wordpress_ynh#30]
Yunohost users don't know that wordpress is very risky because it's the number one solution for creating website.

I suggest to add a special warrant for this app to explain, this app and its plugins and themes should be really maintained up to date.

**Comment by lapineige** [comment]
I'm in favour of that, this is a general advice but once Wordpress is very popular and also quite risky, a special warant would be good, at least to remind people to keep things up to date (for instance by keeping its auto-update by default).

**Comment by lapineige** [comment]
:up:
What do @YunoHost-Apps/apps-group members think about it ?

**Comment by lapineige** [comment]
:up: ? :)

**Comment by maniackcrudelis** [comment]
Feel free to open a PR

**Comment by lapineige** [comment]
Should it be added during the installation process ?
Or in the readme here ? (less visible I guess)

**Comment by maniackcrudelis** [comment]
Probably better into the readme, in "Limitations" part.

**Comment by lapineige** [comment]
This can be closed.
