### ISSUE TITLE
Add a fail2ban jail

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/wordpress_ynh#31]
Could be based on this [current helper](https://github.com/YunoHost-Apps/piwigo_ynh/blob/master/scripts/_common.sh#L578-L630) and inspired by [this website](https://www.it-connect.fr/securisez-votre-wordpress-avec-fail2ban/).

**Comment by maniackcrudelis** [comment]
Nice idea !
Can you open a pull request or put this helper in a repository, even in your own repository.
Just to have a place to find it and contribute together. And to be able to build together this new helper, and soon make it official.

**Comment by JimboJoe** [comment]
Fail2ban helpers PR initiated [here](https://github.com/YunoHost/yunohost/pull/364).

**Comment by JimboJoe** [comment]
Implemented in 8cf157217eba50daddcb0970da7b825e255b125a
