### ISSUE TITLE
Stuck after SSOwat generation

### ISSUE THREAD

**Issue by Myxfall** [YunoHost-Apps/wordpress_ynh#43]
With the latest commit, I am not able anymore to install the module. It is stucked right away after the SSOwat generation and the little black "pacman" of the installation keeps going and never disappear. 

I do not have any other information because everything went good until that.

**Comment by maniackcrudelis** [comment]
Hi Myxfall

Are you running YunoHost on Raspi ?
Have you already install mailutils apt package ?

**Comment by Myxfall** [comment]
Hey Maniackcrudelis,

I am running Yunohost on a VPS host by ovh.com, not on an raspberry.
And no I do not think I installed mailutils, but I can try it and inform you later :)

**Comment by Myxfall** [comment]
It works, thanks for the help !

**Comment by isAAAc** [comment]
hi , what was the resolution way please ?

**Comment by maniackcrudelis** [comment]
Probably installing mailutils
