### ISSUE TITLE
php-fpm memory_limit is too short for somes plugins

### ISSUE THREAD

**Issue by indelog** [YunoHost-Apps/wordpress_ynh#59]
In php-fpm.conf for this application memory_limit is fixed at 30M but somes plugin like nexttgen-gellery requiert more (32M for it) else if wont be run.

Please update php-fpm.conf to increase the value of memory_limit.

**Comment by maniackcrudelis** [comment]
We do not include such plugins during the install of wordpress.
You could always find a plugin which requires more of something.

If you have, for your own usage a need for more memory, feel free to update your php-fpm configuration.
You'll find the config file there: `/etc/php/7.0/fpm/pool.d/wordpress.conf`
