### ISSUE TITLE
Error message from “simple-ldap-login” plugin

### ISSUE THREAD

**Issue by bugsysop** [YunoHost-Apps/wordpress_ynh#62]
In debug mod I have this error message
```
Undefined variable: version in /var/www/wordpress/wp-content/plugins/simple-ldap-login/Simple-LDAP-Login.php on line 54
```
But WordPress is running normally

**Comment by opi** [comment]
@bugsysop : This is an upstream bug in Simple-LDAP-Login plugin : https://github.com/clifgriffin/simple-ldap-login/issues/50

( Note that this simple issue is open for more than a Year, I fear this WP Plugin is not maintained anymore... )

@maniackcrudelis You can close this `wordpress_ynh` issue.
