### ISSUE TITLE
Error: This url is not available or conflicts with the already installed app(s):

### ISSUE THREAD

**Issue by pidlas** [YunoHost-Apps/wordpress_ynh#66]
Hi,

Got this error while trying to install phpmyadmin from the master or testing branch.
`Error: This url is not available or conflicts with the already installed app(s):
 * sante0naturel.bio/ → La sante Oh! naturelle (wordpress)`

The completed terminal output is:
`root@srv-web-idlas:/usr/lib/moulinette/yunohost# yunohost app install https://github.com/YunoHost-Apps/phpmyadmin_ynh.git
WARNING! Installing 3rd party applications may compromise the integrity and security of your system. You should probably NOT install it unless you know what you are doing. Are you willing to take that risk? [Y/N] : Y
Available domains:
- sante0naturel.bio
Choose a domain for phpMyAdmin (default: sante0naturel.bio): 
Choose a path for phpMyAdmin (default: /phpmyadmin): 
Available users:
- phlip
Choose the only allowed admin user: phlip
Error: This url is not available or conflicts with the already installed app(s):
 * sante0naturel.bio/ → La sante Oh! naturelle (wordpress)
root@srv-web-idlas:/usr/lib/moulinette/yunohost# `

Thanks for your support, help, advices, comments.

**Comment by maniackcrudelis** [comment]
As the error message says, this url isn't available.
You have installed wordpress on `sante0naturel.bio/`, so you have dedicated this domain to wordpress. Wordpress will now catch any url on this domain as one of its own.

Trying to install phpmyadmin on `sante0naturel.bio/phpmyadmin` won't work because that url belongs now to wordpress.

So either you move wordpress into a sub path, then set wordpress as the default app for this domain. Which mean if an user try to reach your domain, he will end on wordpress, whatever the sub path of wordpress.
Or you install phpmyadmin into a subdomain or another domain.

**Comment by pidlas** [comment]
Thanks for your quick answer. I changed the url to `sante0naturel.bio/blog`. I could then install `phpmyadmin` as the terminal output displays:
`root@srv-web-idlas:/usr/lib/moulinette/yunohost# yunohost app install https://github.com/YunoHost-Apps/phpmyadmin_ynh.git
WARNING! Installing 3rd party applications may compromise the integrity and security of your system. You should probably NOT install it unless you know what you are doing. Are you willing to take that risk? [Y/N] : Y
Available domains:
- sante0naturel.bio
Choose a domain for phpMyAdmin (default: sante0naturel.bio): 
Choose a path for phpMyAdmin (default: /phpmyadmin): 
Available users:
- phlip
Choose the only allowed admin user: phlip
Info: Installing application phpmyadmin…
Info: [....................] > Validating installation parameters...
Info: [....................] > Storing installation settings...
Info: [....................] > Creating a MySQL database...
Info: [....................] > Setting up source files...
Info: [##..................] > Configuring nginx web server...
Info: Reload the service nginx
Info: [##..................] > Configuring system user...
Info: [###.................] > Configuring php-fpm...
Info: Reload the service php7.0-fpm
Info: [####................] > Filling database...
Info: [####................] > Configuring phpmyadmin...
Info: [#####...............] > Installing dependencies with Composer...
Warning: Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Info: [##################..] > Configuring SSOwat...
Info: [###################.] > Reloading nginx web server...
Info: Reload the service nginx
Info: [####################] > Installation of phpmyadmin completed
Success! The SSOwat configuration has been generated
Success! Installation complete`

So I will close this issue as I am in the learning curve of YunoHost. I do not know if it is the best thing to do but I will stick to it right now.
