### ISSUE TITLE
Broken paths after domain switch

### ISSUE THREAD

**Issue by freddie-freeloader** [YunoHost-Apps/wordpress_ynh#73]
First, I like to thank all contributors and maintainers for their work. :blush: 

After changing the domain associated with WordPress through the admin panel, many paths of the WordPress instance were broken.

I thought switching back to the old one, would fix this again. Sadly it was still broken.

I think the issue was that the links were not properly changed and ended up looking like this:

`example.com/example.com/wordpress`

Some string appending seemed to been going wrong. :cry: 

This might also help to reproduce the error:
I changed the domain in the following order:
`foo.org` -> `www.foo.org` -> `foo.org`

**Comment by kay0u** [comment]
Hi,

Thank you for your report.

It's a duplicate of https://github.com/YunoHost-Apps/wordpress_ynh/issues/70

And this should fix this issue: https://github.com/YunoHost-Apps/wordpress_ynh/pull/71

A workaround is to add by hand the `https://` in `wp_option` table, on both `siteurl` and `home` with phpmyadmin for example, if you know how to do it :-)

**Comment by freddie-freeloader** [comment]
Thank you for your reply. In case I encounter the issue again, I'll try that workaround.

Cheers! :relaxed:
