### ISSUE TITLE
[Multisites] FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/wordpress_ynh#76]
Hello, 
i tried to fix some right trouble on my multiste instance this night, 
i based myself on a single site instance i have on the same server, but now, i have this issue :
```
2019/11/29 03:32:53 [error] 23041#23041: *54620 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 88.121.55.144, server: port.krashboyz.org, request: "GET /blog/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm-wordpress__2.sock:", host: "port.krashboyz.org", referrer: "https://krashboyz.org/yunohost/sso/portal.html"
```
i think something is not good with my rights fix, 
site multisite was working before my "fix" :/

could someone help me please ?

thx a lot

**Comment by isAAAc** [comment]
if i can't fix, i think i will backup the sites, and send them on fresh mono-instance for each one , and kill the multi-sites instance (perhaps is it the better way to do)

**Comment by maniackcrudelis** [comment]
You can try to upgrade your package, the upgrade script may fix your installation.
