### ISSUE TITLE
enh: limit Wordpress admin interface to portal users

### ISSUE THREAD

**Issue by nqb** [YunoHost-Apps/wordpress_ynh#98]
In order to improve security, it would be nice to limit access to `http://domain.com/blog/wp-login.php` only to YunoHost users logged through portal.

**Comment by lapineige** [comment]
I don't know if we should do that by default, as users might want non-yunohost users to access their wordpress admin interface.

But maybe it could be an install option / app action / configuration tip in the readme ?

**Comment by nqb** [comment]
Hello,

> I don't know if we should do that by default, as users might want non-yunohost users to access their wordpress admin interface.

Could you elaborate (provide a use case) ?

**Comment by kay0u** [comment]
After YunoHost 4.1 and the new permission system, it will be easy to do something like this

**Comment by lapineige** [comment]
> Could you elaborate (provide a use case) ?

If you use yunohost to install it in a simpler way (than usual), maybe as well as other tools, but you are not the only admin/author/moderator of your wordpress *and* you don't want to give a yunohost account* to the other people, then it can be useful to keep the non private (sso protected) access.

*as well as access to other applications, and the necessity to log in yunohost + wordpress.


@kay0u what do you mean ?

**Comment by nqb** [comment]
Got your point @lapineige, it makes sense.

**Comment by kay0u** [comment]
> @kay0u what do you mean ?

With the new permission system of the 4.1, we can define a path (here `/wp-login.php`), and let the YunoHost Admin choose if he wants to protect it with the sso or not

**Comment by lapineige** [comment]
> we can define a path 

During install process ? Or afterwards ?
