### ISSUE TITLE
bug: cron didn't work when using a private blog

### ISSUE THREAD

**Issue by nqb** [YunoHost-Apps/wordpress_ynh#99]
During installation, if you answer "No" to "Is it a public website ?" question, your WordPress blog is only visible for YunoHost users.

Few days after installation, you got this message on WordPress panel:

> L’évènement planifié wp_scheduled_delete a échoué. Votre site fonctionne toujours, mais cela pourrait indiquer que les publications planifiées ou les mises à jour automatiques ne fonctionnent pas comme elles le devraient.

The cron job installed on YunoHost server doesn't run correctly each night at 03:00 because website is not reachable without a YunoHost authentication:

```
# Reach everyday wp-cron.php?doing_wp_cron to trig the internal wordpress cron.
0 3  *  *  * root wget -q -O - https://domain.fr/blog/wp-cron.php?doing_wp_cron >/dev/null 2>&1
```

**Comment by yalh76** [comment]
duplicate of #100
